//
//  Factlets.swift
//  Factlet
//
//  Data model and collection of general knowledge factlets
//

import Foundation

// MARK: - Factlet Level
enum FactletLevel: Int, Codable, CaseIterable {
    case level1 = 1
    case level2 = 2
    case level3 = 3
    
    var displayName: String {
        return "Level \(rawValue)"
    }
}

struct Factlet: Codable, Identifiable, Equatable {
    let id: UUID
    let fact: String
    let category: String
    let level: FactletLevel
    
    init(id: UUID = UUID(), fact: String, category: String, level: FactletLevel) {
        self.id = id
        self.fact = fact
        self.category = category
        self.level = level
    }
}

// MARK: - Factlet Collection
struct FactletCollection {
    static let all: [Factlet] = [
        // Science - Level 1
        Factlet(fact: "Honey never spoils. Archaeologists have found 3,000-year-old honey in Egyptian tombs that was still perfectly edible.", category: "Science", level: .level1),
        Factlet(fact: "Bananas are berries, but strawberries are not. Botanically, berries are fruits produced from a single ovary.", category: "Science", level: .level1),
        Factlet(fact: "Lightning strikes the Earth about 8 million times per day, or roughly 100 times per second.", category: "Science", level: .level1),
        Factlet(fact: "Your body contains about 37.2 trillion cells, and you lose about 200 billion cells every day.", category: "Science", level: .level1),
        Factlet(fact: "The speed of light is approximately 186,282 miles per second, or about 670 million miles per hour.", category: "Science", level: .level1),
        Factlet(fact: "A single cloud can weigh more than 1 million pounds, but floats because the air beneath it is even heavier.", category: "Science", level: .level1),
        Factlet(fact: "The human brain generates about 20 watts of electrical power—enough to power a dim light bulb.", category: "Science", level: .level1),
        Factlet(fact: "Sound travels about 4 times faster in water than in air.", category: "Science", level: .level1),
        Factlet(fact: "A single raindrop falling from a cloud can reach speeds of up to 22 miles per hour.", category: "Science", level: .level1),
        Factlet(fact: "The Moon is slowly moving away from Earth at a rate of about 1.5 inches per year.", category: "Science", level: .level1),
        Factlet(fact: "Water expands when it freezes, which is why ice floats on water.", category: "Science", level: .level1),
        Factlet(fact: "The Earth rotates at about 1,000 miles per hour at the equator.", category: "Science", level: .level1),
        Factlet(fact: "A single teaspoon of neutron star material would weigh 6 billion tons on Earth.", category: "Science", level: .level1),
        Factlet(fact: "The Sun is so large that 1.3 million Earths could fit inside it.", category: "Science", level: .level1),
        Factlet(fact: "Light from the Sun takes about 8 minutes and 20 seconds to reach Earth.", category: "Science", level: .level1),
        Factlet(fact: "There are more stars in the universe than grains of sand on all the beaches on Earth.", category: "Science", level: .level1),
        Factlet(fact: "The human body is made up of about 60% water.", category: "Science", level: .level1),
        Factlet(fact: "A single snowflake can have up to 200 ice crystals.", category: "Science", level: .level1),
        Factlet(fact: "The speed of sound is about 767 miles per hour at sea level.", category: "Science", level: .level1),
        Factlet(fact: "The Earth's atmosphere extends about 6,200 miles into space.", category: "Science", level: .level1),
        Factlet(fact: "A single drop of water contains billions of water molecules.", category: "Science", level: .level1),
        Factlet(fact: "The coldest temperature ever recorded on Earth was -128.6°F in Antarctica.", category: "Science", level: .level1),
        Factlet(fact: "The hottest temperature ever recorded on Earth was 134°F in Death Valley, California.", category: "Science", level: .level1),
        Factlet(fact: "The Earth's magnetic field protects us from harmful solar radiation.", category: "Science", level: .level1),
        Factlet(fact: "A single atom is mostly empty space—99.9% of it is nothing.", category: "Science", level: .level1),
        Factlet(fact: "The human body contains enough DNA to stretch from the Sun to Pluto and back 17 times.", category: "Science", level: .level1),
        Factlet(fact: "The Moon is gradually slowing down Earth's rotation, making days longer over time.", category: "Science", level: .level1),
        Factlet(fact: "A single lightning bolt can heat the air around it to 50,000°F—hotter than the surface of the Sun.", category: "Science", level: .level1),
        Factlet(fact: "The Earth's core is made mostly of iron and nickel.", category: "Science", level: .level1),
        Factlet(fact: "A single raindrop can contain thousands of water molecules.", category: "Science", level: .level1),
        Factlet(fact: "The human eye can see about 10 million different colors.", category: "Science", level: .level1),
        Factlet(fact: "The speed of light is constant in a vacuum, about 186,282 miles per second.", category: "Science", level: .level1),
        Factlet(fact: "A single cloud can contain millions of gallons of water.", category: "Science", level: .level1),
        Factlet(fact: "The Earth's crust is only about 0.4% of the planet's total mass.", category: "Science", level: .level1),
        Factlet(fact: "A single grain of sand contains billions of atoms.", category: "Science", level: .level1),
        Factlet(fact: "The human brain uses about 20% of the body's total energy.", category: "Science", level: .level1),
        Factlet(fact: "The Moon has no atmosphere, so there's no weather or wind.", category: "Science", level: .level1),
        Factlet(fact: "A single snowflake takes about an hour to form and fall to the ground.", category: "Science", level: .level1),
        Factlet(fact: "The Earth's rotation is gradually slowing down, making days longer by about 1.7 milliseconds per century.", category: "Science", level: .level1),
        Factlet(fact: "A single drop of blood contains millions of red blood cells.", category: "Science", level: .level1),
        Factlet(fact: "The Sun produces more energy in one second than humans have used in all of history.", category: "Science", level: .level1),
        Factlet(fact: "The human body contains about 37.2 trillion cells.", category: "Science", level: .level1),
        Factlet(fact: "A single atom can exist in multiple places at the same time, according to quantum mechanics.", category: "Science", level: .level1),
        Factlet(fact: "The Earth's magnetic field reverses direction every few hundred thousand years.", category: "Science", level: .level1),
        Factlet(fact: "A single photon of light can travel across the entire universe without being absorbed.", category: "Science", level: .level1),
        Factlet(fact: "The human body produces about 25 million new cells every second.", category: "Science", level: .level1),
        Factlet(fact: "The Moon's gravity causes tides on Earth, pulling the ocean water toward it.", category: "Science", level: .level1),
        Factlet(fact: "A single molecule of water is made up of two hydrogen atoms and one oxygen atom.", category: "Science", level: .level1),
        Factlet(fact: "The Earth's atmosphere is made up of about 78% nitrogen and 21% oxygen.", category: "Science", level: .level1),
        Factlet(fact: "A single lightning strike can contain enough energy to power a 100-watt light bulb for 90 days.", category: "Science", level: .level1),
        
        // Science - Level 2
        Factlet(fact: "A day on Venus is longer than its year. Venus takes 243 Earth days to rotate once, but only 225 Earth days to orbit the Sun.", category: "Science", level: .level2),
        Factlet(fact: "Octopuses have three hearts and blue blood. Two hearts pump blood to the gills, while the third pumps it to the rest of the body.", category: "Science", level: .level2),
        Factlet(fact: "Water can boil and freeze at the same time. This phenomenon, called the triple point, occurs at a specific temperature and pressure.", category: "Science", level: .level2),
        Factlet(fact: "Diamonds are not forever—they can burn. At about 1,652°F, a diamond will start to burn.", category: "Science", level: .level2),
        Factlet(fact: "There are more atoms in a single glass of water than there are glasses of water in all the oceans on Earth.", category: "Science", level: .level2),
        Factlet(fact: "Gold is so rare that all the gold ever mined would fit into a cube about 21 meters on each side.", category: "Science", level: .level2),
        Factlet(fact: "Helium is the only element that cannot be solidified by lowering temperature alone—it requires pressure too.", category: "Science", level: .level2),
        Factlet(fact: "A single bolt of lightning contains enough energy to power a 100-watt light bulb for more than 3 months.", category: "Science", level: .level2),
        Factlet(fact: "The Earth's core is as hot as the surface of the Sun, reaching temperatures of about 9,800°F.", category: "Science", level: .level2),
        Factlet(fact: "The human eye can detect a single photon of light in perfect darkness.", category: "Science", level: .level2),
        Factlet(fact: "Glass is actually a liquid, not a solid. It flows very slowly over hundreds of years.", category: "Science", level: .level2),
        Factlet(fact: "The DNA in your body, if uncoiled, would stretch from the Earth to the Sun and back more than 300 times.", category: "Science", level: .level2),
        Factlet(fact: "A single teaspoon of soil can contain more living organisms than there are people on Earth.", category: "Science", level: .level2),
        Factlet(fact: "Oxygen makes up about 21% of Earth's atmosphere, but it's only the third most abundant element in the universe.", category: "Science", level: .level2),
        Factlet(fact: "A single strand of spider silk is stronger than steel of the same diameter.", category: "Science", level: .level2),
        Factlet(fact: "The human body contains enough iron to make a 3-inch nail.", category: "Science", level: .level2),
        Factlet(fact: "A single teaspoon of neutron star material would weigh 6 billion tons on Earth.", category: "Science", level: .level2),
        Factlet(fact: "The Sun converts about 4 million tons of matter into energy every second.", category: "Science", level: .level2),
        Factlet(fact: "The human brain contains about 100 billion neurons, each connected to thousands of others.", category: "Science", level: .level2),
        Factlet(fact: "A single atom of hydrogen is the simplest and most abundant element in the universe.", category: "Science", level: .level2),
        Factlet(fact: "The Earth's magnetic field is generated by the movement of molten iron in its core.", category: "Science", level: .level2),
        Factlet(fact: "A single DNA molecule can contain billions of base pairs, encoding genetic information.", category: "Science", level: .level2),
        Factlet(fact: "The speed of light is so fast that it could travel around Earth 7.5 times in one second.", category: "Science", level: .level2),
        Factlet(fact: "The human body produces about 1.5 liters of saliva every day.", category: "Science", level: .level2),
        Factlet(fact: "A single cloud can weigh more than a million pounds, but floats because air is even heavier.", category: "Science", level: .level2),
        Factlet(fact: "The Earth's core temperature is about 9,800°F, similar to the surface of the Sun.", category: "Science", level: .level2),
        Factlet(fact: "A single grain of sand contains about 10 quintillion atoms.", category: "Science", level: .level2),
        Factlet(fact: "The human eye can detect a single photon of light in perfect darkness.", category: "Science", level: .level2),
        Factlet(fact: "The Moon is slowly moving away from Earth at about 1.5 inches per year.", category: "Science", level: .level2),
        Factlet(fact: "A single lightning bolt can heat the air to 50,000°F, five times hotter than the Sun's surface.", category: "Science", level: .level2),
        Factlet(fact: "The human body contains enough carbon to fill about 9,000 pencils.", category: "Science", level: .level2),
        Factlet(fact: "The Earth's rotation is gradually slowing down, making days longer over millions of years.", category: "Science", level: .level2),
        Factlet(fact: "A single drop of water contains about 5 sextillion water molecules.", category: "Science", level: .level2),
        Factlet(fact: "The Sun's core temperature is about 27 million°F, where nuclear fusion occurs.", category: "Science", level: .level2),
        Factlet(fact: "The human body has about 60,000 miles of blood vessels, enough to circle Earth twice.", category: "Science", level: .level2),
        Factlet(fact: "A single atom is 99.9% empty space, with the nucleus being incredibly small.", category: "Science", level: .level2),
        Factlet(fact: "The Earth's atmosphere extends about 6,200 miles into space, gradually thinning out.", category: "Science", level: .level2),
        Factlet(fact: "A single snowflake can have a unique structure, with no two being exactly alike.", category: "Science", level: .level2),
        Factlet(fact: "The human brain uses about 20% of the body's total energy, despite being only 2% of its weight.", category: "Science", level: .level2),
        Factlet(fact: "The speed of sound varies with temperature and altitude, traveling faster in warmer air.", category: "Science", level: .level2),
        Factlet(fact: "A single raindrop can contain thousands of water molecules, each made of hydrogen and oxygen.", category: "Science", level: .level2),
        Factlet(fact: "The Earth's magnetic field protects us from harmful solar radiation and cosmic rays.", category: "Science", level: .level2),
        Factlet(fact: "A single photon of light can exist as both a particle and a wave simultaneously.", category: "Science", level: .level2),
        Factlet(fact: "The human body produces about 25 million new cells every second, replacing old ones.", category: "Science", level: .level2),
        Factlet(fact: "The Moon's gravity causes ocean tides, pulling water toward it as it orbits Earth.", category: "Science", level: .level2),
        Factlet(fact: "A single molecule of DNA can contain billions of base pairs, encoding genetic information.", category: "Science", level: .level2),
        Factlet(fact: "The Sun produces energy through nuclear fusion, converting hydrogen into helium.", category: "Science", level: .level2),
        Factlet(fact: "The human body contains about 37.2 trillion cells, each with its own specific function.", category: "Science", level: .level2),
        Factlet(fact: "A single atom can exist in multiple quantum states simultaneously, according to quantum mechanics.", category: "Science", level: .level2),
        
        // Science - Level 3
        Factlet(fact: "A teaspoon of neutron star would weigh about 6 billion tons.", category: "Science", level: .level3),
        Factlet(fact: "The human body produces about 1.5 liters of saliva every day.", category: "Science", level: .level3),
        Factlet(fact: "At absolute zero (-459.67°F), atoms would stop moving completely.", category: "Science", level: .level3),
        Factlet(fact: "The Great Red Spot on Jupiter is a storm that has been raging for at least 400 years.", category: "Science", level: .level3),
        Factlet(fact: "A single grain of sand contains about 10 quintillion atoms.", category: "Science", level: .level3),
        Factlet(fact: "Quantum entanglement allows particles to be instantly connected regardless of distance, defying classical physics.", category: "Science", level: .level3),
        Factlet(fact: "The Heisenberg Uncertainty Principle states that you cannot simultaneously know both the position and momentum of a particle with perfect accuracy.", category: "Science", level: .level3),
        Factlet(fact: "Black holes can have temperatures near absolute zero, yet still emit Hawking radiation due to quantum effects.", category: "Science", level: .level3),
        Factlet(fact: "The Casimir effect demonstrates that empty space contains virtual particles that can create measurable forces.", category: "Science", level: .level3),
        Factlet(fact: "Time dilation means that time passes slower for objects moving at high speeds or in strong gravitational fields.", category: "Science", level: .level3),
        Factlet(fact: "The double-slit experiment shows that particles behave as both waves and particles, depending on observation.", category: "Science", level: .level3),
        Factlet(fact: "Schrödinger's cat thought experiment illustrates quantum superposition, where a system exists in all possible states until observed.", category: "Science", level: .level3),
        Factlet(fact: "The Pauli Exclusion Principle prevents two identical fermions from occupying the same quantum state simultaneously.", category: "Science", level: .level3),
        Factlet(fact: "Quantum tunneling allows particles to pass through energy barriers that would be impossible in classical physics.", category: "Science", level: .level3),
        Factlet(fact: "The Standard Model of particle physics describes 17 fundamental particles and their interactions.", category: "Science", level: .level3),
        Factlet(fact: "Dark matter makes up about 27% of the universe but has never been directly observed.", category: "Science", level: .level3),
        Factlet(fact: "Dark energy accounts for about 68% of the universe and is causing its accelerated expansion.", category: "Science", level: .level3),
        Factlet(fact: "The Higgs boson, discovered in 2012, gives mass to other particles through the Higgs field.", category: "Science", level: .level3),
        Factlet(fact: "String theory proposes that fundamental particles are one-dimensional vibrating strings in 10 or 11 dimensions.", category: "Science", level: .level3),
        Factlet(fact: "The theory of relativity shows that mass and energy are equivalent, expressed as E=mc².", category: "Science", level: .level3),
        Factlet(fact: "Gravitational waves, ripples in spacetime, were first directly detected in 2015, confirming Einstein's prediction.", category: "Science", level: .level3),
        Factlet(fact: "The Big Bang theory suggests the universe began as an infinitely dense point about 13.8 billion years ago.", category: "Science", level: .level3),
        Factlet(fact: "Inflation theory proposes the universe expanded faster than light in the first fraction of a second after the Big Bang.", category: "Science", level: .level3),
        Factlet(fact: "The multiverse hypothesis suggests our universe may be one of many parallel universes with different physical laws.", category: "Science", level: .level3),
        Factlet(fact: "Quantum decoherence explains how quantum systems transition to classical behavior through interaction with the environment.", category: "Science", level: .level3),
        Factlet(fact: "The observer effect in quantum mechanics means that the act of measurement changes the system being measured.", category: "Science", level: .level3),
        Factlet(fact: "Bell's theorem proves that quantum mechanics cannot be explained by local hidden variables.", category: "Science", level: .level3),
        Factlet(fact: "The many-worlds interpretation suggests that every quantum measurement splits the universe into parallel realities.", category: "Science", level: .level3),
        Factlet(fact: "Quantum superposition allows particles to exist in multiple states simultaneously until measured.", category: "Science", level: .level3),
        Factlet(fact: "The uncertainty principle is fundamental to quantum mechanics, not just a limitation of measurement.", category: "Science", level: .level3),
        Factlet(fact: "Quantum field theory describes particles as excitations in underlying quantum fields that permeate space.", category: "Science", level: .level3),
        Factlet(fact: "The wave function collapse occurs when a quantum system is measured, reducing probabilities to a single outcome.", category: "Science", level: .level3),
        Factlet(fact: "Quantum spin is an intrinsic property of particles that has no classical equivalent.", category: "Science", level: .level3),
        Factlet(fact: "The photoelectric effect, explained by Einstein, shows that light behaves as discrete particles called photons.", category: "Science", level: .level3),
        Factlet(fact: "Quantum chromodynamics describes the strong nuclear force that holds quarks together in protons and neutrons.", category: "Science", level: .level3),
        Factlet(fact: "The electroweak theory unifies electromagnetism and the weak nuclear force at high energies.", category: "Science", level: .level3),
        Factlet(fact: "Supersymmetry proposes that every particle has a superpartner with different spin properties.", category: "Science", level: .level3),
        Factlet(fact: "The holographic principle suggests that information in a volume of space can be encoded on its boundary.", category: "Science", level: .level3),
        Factlet(fact: "Quantum error correction allows quantum computers to maintain coherence despite environmental interference.", category: "Science", level: .level3),
        Factlet(fact: "The measurement problem in quantum mechanics questions how and why wave function collapse occurs.", category: "Science", level: .level3),
        Factlet(fact: "Quantum nonlocality means that entangled particles can instantaneously affect each other regardless of distance.", category: "Science", level: .level3),
        Factlet(fact: "The quantum Zeno effect can prevent a system from evolving by repeatedly measuring it.", category: "Science", level: .level3),
        Factlet(fact: "Quantum teleportation transfers quantum information between particles without physical movement.", category: "Science", level: .level3),
        Factlet(fact: "The no-cloning theorem proves that quantum information cannot be perfectly copied.", category: "Science", level: .level3),
        Factlet(fact: "Quantum cryptography uses quantum mechanics to create unbreakable encryption methods.", category: "Science", level: .level3),
        Factlet(fact: "The quantum Hall effect shows quantized resistance in two-dimensional electron systems at low temperatures.", category: "Science", level: .level3),
        Factlet(fact: "Quantum dots are nanoscale semiconductor particles with quantum mechanical properties.", category: "Science", level: .level3),
        Factlet(fact: "The quantum spin Hall effect could enable dissipationless electron transport for future electronics.", category: "Science", level: .level3),
        Factlet(fact: "Quantum annealing uses quantum fluctuations to find optimal solutions to complex optimization problems.", category: "Science", level: .level3),
        Factlet(fact: "The quantum critical point is where a material transitions between different quantum phases.", category: "Science", level: .level3),
        Factlet(fact: "Quantum biology explores how quantum effects may play a role in biological processes like photosynthesis.", category: "Science", level: .level3),
        
        // History - Level 1
        Factlet(fact: "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.", category: "History", level: .level1),
        Factlet(fact: "The shortest war in history lasted 38 to 45 minutes between Britain and Zanzibar on August 27, 1896.", category: "History", level: .level1),
        Factlet(fact: "The Eiffel Tower was originally intended to be a temporary structure, built for the 1889 World's Fair.", category: "History", level: .level1),
        Factlet(fact: "Vikings never wore horned helmets. This is a 19th-century myth popularized by costume designers.", category: "History", level: .level1),
        Factlet(fact: "The first computer programmer was Ada Lovelace, who wrote algorithms for Charles Babbage's Analytical Engine in the 1840s.", category: "History", level: .level1),
        Factlet(fact: "Napoleon was actually average height for his time—about 5'7\". The myth of his shortness came from British propaganda.", category: "History", level: .level1),
        Factlet(fact: "The Great Wall of China is not visible from space with the naked eye, despite the popular myth.", category: "History", level: .level1),
        Factlet(fact: "The Titanic was considered unsinkable, but it sank on its maiden voyage in 1912 after hitting an iceberg.", category: "History", level: .level1),
        Factlet(fact: "The Berlin Wall stood for 28 years, from 1961 to 1989, dividing East and West Berlin.", category: "History", level: .level1),
        Factlet(fact: "The first successful airplane flight by the Wright Brothers lasted only 12 seconds and covered 120 feet.", category: "History", level: .level1),
        Factlet(fact: "The ancient city of Rome was founded in 753 BCE according to legend.", category: "History", level: .level1),
        Factlet(fact: "The Great Fire of London in 1666 destroyed most of the city but only killed 6 people.", category: "History", level: .level1),
        Factlet(fact: "The first Olympic Games were held in ancient Greece in 776 BCE.", category: "History", level: .level1),
        Factlet(fact: "The Declaration of Independence was signed on July 4, 1776, in Philadelphia.", category: "History", level: .level1),
        Factlet(fact: "The first successful human heart transplant was performed in 1967 by Dr. Christiaan Barnard.", category: "History", level: .level1),
        Factlet(fact: "The ancient Egyptians built the pyramids as tombs for their pharaohs.", category: "History", level: .level1),
        Factlet(fact: "The fall of the Berlin Wall in 1989 marked the end of the Cold War era.", category: "History", level: .level1),
        Factlet(fact: "The first man to walk on the Moon was Neil Armstrong on July 20, 1969.", category: "History", level: .level1),
        Factlet(fact: "The ancient Greeks invented democracy in Athens around 508 BCE.", category: "History", level: .level1),
        Factlet(fact: "The Renaissance period began in Italy in the 14th century and spread across Europe.", category: "History", level: .level1),
        Factlet(fact: "The first successful vaccine was developed by Edward Jenner in 1796 to prevent smallpox.", category: "History", level: .level1),
        Factlet(fact: "The ancient Romans built aqueducts to bring fresh water to their cities.", category: "History", level: .level1),
        Factlet(fact: "The Industrial Revolution began in Britain in the late 18th century.", category: "History", level: .level1),
        Factlet(fact: "The first successful transatlantic telegraph cable was laid in 1866.", category: "History", level: .level1),
        Factlet(fact: "The ancient Chinese invented paper around 105 CE.", category: "History", level: .level1),
        Factlet(fact: "The first successful flight across the Atlantic Ocean was made by Charles Lindbergh in 1927.", category: "History", level: .level1),
        Factlet(fact: "The ancient Greeks built the Parthenon in Athens as a temple to the goddess Athena.", category: "History", level: .level1),
        Factlet(fact: "The first successful human spaceflight was made by Yuri Gagarin in 1961.", category: "History", level: .level1),
        Factlet(fact: "The ancient Egyptians invented hieroglyphics, one of the earliest writing systems.", category: "History", level: .level1),
        Factlet(fact: "The first successful cloning of a mammal was Dolly the sheep in 1996.", category: "History", level: .level1),
        Factlet(fact: "The ancient Romans built the Colosseum in Rome for gladiatorial contests.", category: "History", level: .level1),
        Factlet(fact: "The first successful human organ transplant was a kidney transplant in 1954.", category: "History", level: .level1),
        Factlet(fact: "The ancient Greeks invented the Olympic Games to honor the god Zeus.", category: "History", level: .level1),
        Factlet(fact: "The first successful flight of a powered aircraft was made by the Wright Brothers in 1903.", category: "History", level: .level1),
        Factlet(fact: "The ancient Chinese built the Great Wall to protect against invasions.", category: "History", level: .level1),
        Factlet(fact: "The first successful human heart transplant was performed in South Africa in 1967.", category: "History", level: .level1),
        Factlet(fact: "The ancient Egyptians mummified their dead to preserve their bodies for the afterlife.", category: "History", level: .level1),
        Factlet(fact: "The first successful human spacewalk was made by Alexei Leonov in 1965.", category: "History", level: .level1),
        Factlet(fact: "The ancient Romans built roads throughout their empire, many of which are still in use today.", category: "History", level: .level1),
        Factlet(fact: "The first successful human landing on the Moon was made by Apollo 11 in 1969.", category: "History", level: .level1),
        Factlet(fact: "The ancient Greeks invented philosophy, with thinkers like Socrates, Plato, and Aristotle.", category: "History", level: .level1),
        Factlet(fact: "The first successful human flight was made by the Montgolfier brothers in a hot air balloon in 1783.", category: "History", level: .level1),
        Factlet(fact: "The ancient Egyptians built the Sphinx as a guardian statue near the pyramids.", category: "History", level: .level1),
        Factlet(fact: "The first successful human flight across the English Channel was made by Louis Blériot in 1909.", category: "History", level: .level1),
        Factlet(fact: "The ancient Romans invented concrete, which allowed them to build massive structures.", category: "History", level: .level1),
        Factlet(fact: "The first successful human flight to the North Pole was made by Richard Byrd in 1926.", category: "History", level: .level1),
        Factlet(fact: "The ancient Chinese invented gunpowder around 850 CE.", category: "History", level: .level1),
        Factlet(fact: "The first successful human flight to the South Pole was made by Roald Amundsen in 1911.", category: "History", level: .level1),
        Factlet(fact: "The ancient Greeks invented the theater, with plays performed in amphitheaters.", category: "History", level: .level1),
        Factlet(fact: "The first successful human flight around the world was made by Wiley Post in 1933.", category: "History", level: .level1),
        
        // History - Level 2
        Factlet(fact: "Oxford University is older than the Aztec Empire. Teaching began in Oxford in 1096, while the Aztec Empire was founded in 1428.", category: "History", level: .level2),
        Factlet(fact: "Ancient Romans used crushed mouse brains as toothpaste.", category: "History", level: .level2),
        Factlet(fact: "Woolly mammoths were still alive when the Great Pyramid of Giza was being built, around 2660 BCE.", category: "History", level: .level2),
        Factlet(fact: "The Library of Alexandria, one of the largest libraries of the ancient world, was destroyed over 2,000 years ago.", category: "History", level: .level2),
        Factlet(fact: "The Black Death killed an estimated 75-200 million people in the 14th century, reducing the world population by 30-60%.", category: "History", level: .level2),
        Factlet(fact: "The first recorded Olympic Games were held in 776 BCE in Olympia, Greece.", category: "History", level: .level2),
        Factlet(fact: "The ancient city of Pompeii was buried under volcanic ash in 79 CE and remained preserved for nearly 1,700 years.", category: "History", level: .level2),
        Factlet(fact: "The printing press, invented by Johannes Gutenberg around 1440, revolutionized the spread of information.", category: "History", level: .level2),
        Factlet(fact: "The first photograph was taken in 1826 by Joseph Nicéphore Niépce, requiring an 8-hour exposure.", category: "History", level: .level2),
        Factlet(fact: "The ancient Romans used a sponge on a stick, shared by everyone, as toilet paper.", category: "History", level: .level2),
        Factlet(fact: "The Rosetta Stone, discovered in 1799, was key to deciphering Egyptian hieroglyphs.", category: "History", level: .level2),
        Factlet(fact: "The fall of the Roman Empire in 476 CE marked the end of ancient history and the beginning of the Middle Ages.", category: "History", level: .level2),
        Factlet(fact: "The first telephone call was made by Alexander Graham Bell in 1876, saying 'Mr. Watson, come here.'", category: "History", level: .level2),
        Factlet(fact: "The ancient Egyptians used papyrus, made from the papyrus plant, as paper over 5,000 years ago.", category: "History", level: .level2),
        Factlet(fact: "The Industrial Revolution began in Britain in the late 18th century and transformed society worldwide.", category: "History", level: .level2),
        Factlet(fact: "The Battle of Hastings in 1066 changed the course of English history when William the Conqueror defeated King Harold.", category: "History", level: .level2),
        Factlet(fact: "The Magna Carta, signed in 1215, established the principle that everyone, including the king, was subject to the law.", category: "History", level: .level2),
        Factlet(fact: "The Spanish Inquisition lasted from 1478 to 1834, one of the longest-running institutions in history.", category: "History", level: .level2),
        Factlet(fact: "The Battle of Thermopylae in 480 BCE saw 300 Spartans hold off a massive Persian army for three days.", category: "History", level: .level2),
        Factlet(fact: "The Crusades were a series of religious wars between Christians and Muslims from 1095 to 1291.", category: "History", level: .level2),
        Factlet(fact: "The Hundred Years' War between England and France actually lasted 116 years, from 1337 to 1453.", category: "History", level: .level2),
        Factlet(fact: "The Battle of Waterloo in 1815 marked the final defeat of Napoleon Bonaparte.", category: "History", level: .level2),
        Factlet(fact: "The American Civil War lasted from 1861 to 1865 and resulted in the abolition of slavery.", category: "History", level: .level2),
        Factlet(fact: "The French Revolution began in 1789 and led to the overthrow of the monarchy.", category: "History", level: .level2),
        Factlet(fact: "The Battle of Gettysburg in 1863 was the bloodiest battle of the American Civil War.", category: "History", level: .level2),
        Factlet(fact: "The Russian Revolution of 1917 led to the creation of the Soviet Union.", category: "History", level: .level2),
        Factlet(fact: "The Battle of Stalingrad in 1942-1943 was one of the deadliest battles in human history.", category: "History", level: .level2),
        Factlet(fact: "The fall of Constantinople in 1453 marked the end of the Byzantine Empire.", category: "History", level: .level2),
        Factlet(fact: "The Battle of Agincourt in 1415 saw English longbowmen defeat a much larger French army.", category: "History", level: .level2),
        Factlet(fact: "The signing of the Treaty of Versailles in 1919 ended World War I.", category: "History", level: .level2),
        Factlet(fact: "The Battle of the Somme in 1916 was one of the bloodiest battles of World War I.", category: "History", level: .level2),
        Factlet(fact: "The fall of the Western Roman Empire in 476 CE is traditionally considered the end of ancient history.", category: "History", level: .level2),
        Factlet(fact: "The Battle of Marathon in 490 BCE saw the Greeks defeat the Persians, inspiring the marathon race.", category: "History", level: .level2),
        Factlet(fact: "The signing of the Declaration of Independence in 1776 marked the birth of the United States.", category: "History", level: .level2),
        Factlet(fact: "The Battle of Cannae in 216 BCE saw Hannibal's Carthaginian army destroy a much larger Roman force.", category: "History", level: .level2),
        Factlet(fact: "The fall of the Berlin Wall in 1989 symbolized the end of the Cold War.", category: "History", level: .level2),
        Factlet(fact: "The Battle of Hastings in 1066 was fought on October 14th, a date that changed English history forever.", category: "History", level: .level2),
        Factlet(fact: "The signing of the Magna Carta in 1215 established principles of constitutional law that still influence legal systems today.", category: "History", level: .level2),
        Factlet(fact: "The Battle of Trafalgar in 1805 established British naval supremacy for over a century.", category: "History", level: .level2),
        Factlet(fact: "The fall of the Bastille in 1789 marked the beginning of the French Revolution.", category: "History", level: .level2),
        Factlet(fact: "The Battle of Midway in 1942 was a turning point in the Pacific Theater of World War II.", category: "History", level: .level2),
        Factlet(fact: "The signing of the Treaty of Westphalia in 1648 ended the Thirty Years' War and established modern state sovereignty.", category: "History", level: .level2),
        Factlet(fact: "The Battle of Tours in 732 CE stopped the Muslim advance into Western Europe.", category: "History", level: .level2),
        Factlet(fact: "The fall of the Roman Republic and rise of the Empire began with Julius Caesar's crossing of the Rubicon in 49 BCE.", category: "History", level: .level2),
        Factlet(fact: "The Battle of Lepanto in 1571 was the last major naval battle fought entirely with galleys.", category: "History", level: .level2),
        Factlet(fact: "The signing of the Treaty of Tordesillas in 1494 divided the New World between Spain and Portugal.", category: "History", level: .level2),
        Factlet(fact: "The Battle of Saratoga in 1777 was a turning point in the American Revolutionary War.", category: "History", level: .level2),
        Factlet(fact: "The fall of the Aztec Empire in 1521 was completed by Hernán Cortés and his Spanish conquistadors.", category: "History", level: .level2),
        Factlet(fact: "The Battle of Yorktown in 1781 effectively ended the American Revolutionary War.", category: "History", level: .level2),
        Factlet(fact: "The signing of the Emancipation Proclamation in 1863 declared all slaves in Confederate states to be free.", category: "History", level: .level2),
        
        // History - Level 3
        Factlet(fact: "The first successful heart transplant was performed by Dr. Christiaan Barnard in 1967 in South Africa.", category: "History", level: .level3),
        Factlet(fact: "The ancient Greeks invented democracy in Athens around 508 BCE.", category: "History", level: .level3),
        Factlet(fact: "The first computer, ENIAC, weighed 30 tons and occupied 1,800 square feet when it was built in 1946.", category: "History", level: .level3),
        Factlet(fact: "The Renaissance began in Italy in the 14th century and spread across Europe, marking a cultural rebirth.", category: "History", level: .level3),
        Factlet(fact: "The first successful vaccine was developed by Edward Jenner in 1796 to prevent smallpox.", category: "History", level: .level3),
        Factlet(fact: "The Peloponnesian War (431-404 BCE) between Athens and Sparta fundamentally reshaped the Greek world.", category: "History", level: .level3),
        Factlet(fact: "The Punic Wars (264-146 BCE) between Rome and Carthage determined Mediterranean dominance for centuries.", category: "History", level: .level3),
        Factlet(fact: "The Investiture Controversy (1076-1122) was a power struggle between the papacy and European monarchs.", category: "History", level: .level3),
        Factlet(fact: "The Great Schism of 1054 permanently divided Christianity into Eastern Orthodox and Roman Catholic churches.", category: "History", level: .level3),
        Factlet(fact: "The Reconquista (711-1492) was the 781-year Christian reconquest of the Iberian Peninsula from Muslim rule.", category: "History", level: .level3),
        Factlet(fact: "The Battle of Manzikert in 1071 marked the beginning of Turkish expansion into Anatolia.", category: "History", level: .level3),
        Factlet(fact: "The Fourth Crusade (1202-1204) resulted in the sack of Constantinople by Western Christians.", category: "History", level: .level3),
        Factlet(fact: "The Black Death (1347-1351) killed an estimated 30-60% of Europe's population, fundamentally altering society.", category: "History", level: .level3),
        Factlet(fact: "The Wars of the Roses (1455-1487) were a series of civil wars for control of the English throne.", category: "History", level: .level3),
        Factlet(fact: "The Fall of Constantinople in 1453 to the Ottomans marked the end of the Byzantine Empire after 1,100 years.", category: "History", level: .level3),
        Factlet(fact: "The Spanish Armada's defeat in 1588 prevented Spanish invasion of England and shifted naval power.", category: "History", level: .level3),
        Factlet(fact: "The Thirty Years' War (1618-1648) devastated Central Europe and killed about 8 million people.", category: "History", level: .level3),
        Factlet(fact: "The Glorious Revolution of 1688 established constitutional monarchy in England without bloodshed.", category: "History", level: .level3),
        Factlet(fact: "The War of the Spanish Succession (1701-1714) reshaped European power dynamics and colonial territories.", category: "History", level: .level3),
        Factlet(fact: "The Seven Years' War (1756-1763) was the first truly global war, fought on multiple continents.", category: "History", level: .level3),
        Factlet(fact: "The Partition of Poland (1772-1795) erased a major European state from the map for 123 years.", category: "History", level: .level3),
        Factlet(fact: "The Haitian Revolution (1791-1804) was the only successful slave revolt that resulted in an independent nation.", category: "History", level: .level3),
        Factlet(fact: "The Congress of Vienna (1814-1815) redrew Europe's map after Napoleon's defeat and established a balance of power.", category: "History", level: .level3),
        Factlet(fact: "The Crimean War (1853-1856) was the first major conflict covered by modern war correspondents and photographers.", category: "History", level: .level3),
        Factlet(fact: "The Meiji Restoration (1868) transformed Japan from an isolated feudal society into a modern imperial power.", category: "History", level: .level3),
        Factlet(fact: "The Scramble for Africa (1881-1914) saw European powers divide the continent into colonies in just 33 years.", category: "History", level: .level3),
        Factlet(fact: "The Boxer Rebellion (1899-1901) was an anti-foreign and anti-Christian uprising in China.", category: "History", level: .level3),
        Factlet(fact: "The Russo-Japanese War (1904-1905) was the first time an Asian power defeated a European power in modern times.", category: "History", level: .level3),
        Factlet(fact: "The Armenian Genocide (1915-1923) resulted in the systematic killing of 1.5 million Armenians by the Ottoman Empire.", category: "History", level: .level3),
        Factlet(fact: "The Russian Civil War (1917-1923) determined whether Russia would become communist or remain democratic.", category: "History", level: .level3),
        Factlet(fact: "The Great Depression (1929-1939) was the worst economic downturn in modern history, affecting the entire world.", category: "History", level: .level3),
        Factlet(fact: "The Spanish Civil War (1936-1939) was a prelude to World War II, with international powers testing new weapons.", category: "History", level: .level3),
        Factlet(fact: "The Holocaust (1941-1945) was the systematic murder of 6 million Jews and millions of others by Nazi Germany.", category: "History", level: .level3),
        Factlet(fact: "The Partition of India (1947) created India and Pakistan, displacing 15 million people and causing massive violence.", category: "History", level: .level3),
        Factlet(fact: "The Korean War (1950-1953) was the first major conflict of the Cold War and remains technically unresolved.", category: "History", level: .level3),
        Factlet(fact: "The Suez Crisis (1956) marked the end of British and French colonial dominance in the Middle East.", category: "History", level: .level3),
        Factlet(fact: "The Cuban Missile Crisis (1962) brought the world to the brink of nuclear war between the US and Soviet Union.", category: "History", level: .level3),
        Factlet(fact: "The Six-Day War (1967) reshaped the Middle East, with Israel gaining control of significant territories.", category: "History", level: .level3),
        Factlet(fact: "The Cultural Revolution (1966-1976) in China caused massive social upheaval and the deaths of millions.", category: "History", level: .level3),
        Factlet(fact: "The Iranian Revolution (1979) overthrew the Shah and established an Islamic republic, changing Middle Eastern dynamics.", category: "History", level: .level3),
        Factlet(fact: "The Fall of the Berlin Wall (1989) symbolized the end of the Cold War and the collapse of the Iron Curtain.", category: "History", level: .level3),
        Factlet(fact: "The Dissolution of the Soviet Union (1991) ended the Cold War and created 15 new independent nations.", category: "History", level: .level3),
        Factlet(fact: "The Rwandan Genocide (1994) saw 800,000 people killed in just 100 days, the fastest genocide in history.", category: "History", level: .level3),
        Factlet(fact: "The September 11 attacks (2001) fundamentally changed global security policies and international relations.", category: "History", level: .level3),
        Factlet(fact: "The Arab Spring (2010-2012) was a series of anti-government protests that spread across the Middle East and North Africa.", category: "History", level: .level3),
        Factlet(fact: "The Mongol Empire (1206-1368) was the largest contiguous land empire in history, stretching from Europe to Asia.", category: "History", level: .level3),
        Factlet(fact: "The Han Dynasty (206 BCE-220 CE) established patterns of Chinese governance that lasted for 2,000 years.", category: "History", level: .level3),
        Factlet(fact: "The Gupta Empire (320-550 CE) is considered India's Golden Age, with major advances in science, art, and mathematics.", category: "History", level: .level3),
        Factlet(fact: "The Abbasid Caliphate (750-1258) was the Islamic Golden Age, with Baghdad as the world's largest city and center of learning.", category: "History", level: .level3),
        Factlet(fact: "The Tang Dynasty (618-907 CE) was a high point of Chinese civilization, with the Silk Road at its peak.", category: "History", level: .level3),
        Factlet(fact: "The Carolingian Renaissance (780-900) was a revival of learning and culture under Charlemagne's rule.", category: "History", level: .level3),
        
        // Nature - Level 1
        Factlet(fact: "A group of flamingos is called a flamboyance.", category: "Nature", level: .level1),
        Factlet(fact: "Trees can communicate with each other through an underground network of fungi, sometimes called the 'Wood Wide Web.'", category: "Nature", level: .level1),
        Factlet(fact: "Cows have best friends and experience stress when separated from them.", category: "Nature", level: .level1),
        Factlet(fact: "The Amazon rainforest produces about 20% of the world's oxygen.", category: "Nature", level: .level1),
        Factlet(fact: "A jellyfish is 95% water. If washed ashore, it would nearly disappear as the water evaporates.", category: "Nature", level: .level1),
        Factlet(fact: "A group of owls is called a parliament.", category: "Nature", level: .level1),
        Factlet(fact: "Butterflies taste with their feet. They have taste receptors on their legs to help them find food.", category: "Nature", level: .level1),
        Factlet(fact: "A blue whale's heart is the size of a small car and can weigh up to 1,300 pounds.", category: "Nature", level: .level1),
        Factlet(fact: "Dolphins have names for each other. They use signature whistles to identify themselves.", category: "Nature", level: .level1),
        Factlet(fact: "A single oak tree can produce up to 10,000 acorns in a year.", category: "Nature", level: .level1),
        Factlet(fact: "Penguins can jump up to 6 feet out of the water onto land.", category: "Nature", level: .level1),
        Factlet(fact: "A group of crows is called a murder.", category: "Nature", level: .level1),
        Factlet(fact: "A group of lions is called a pride.", category: "Nature", level: .level1),
        Factlet(fact: "A group of wolves is called a pack.", category: "Nature", level: .level1),
        Factlet(fact: "A group of fish is called a school.", category: "Nature", level: .level1),
        Factlet(fact: "A group of bees is called a swarm.", category: "Nature", level: .level1),
        Factlet(fact: "A group of ants is called a colony.", category: "Nature", level: .level1),
        Factlet(fact: "A group of elephants is called a herd.", category: "Nature", level: .level1),
        Factlet(fact: "A group of monkeys is called a troop.", category: "Nature", level: .level1),
        Factlet(fact: "A group of birds is called a flock.", category: "Nature", level: .level1),
        Factlet(fact: "A group of whales is called a pod.", category: "Nature", level: .level1),
        Factlet(fact: "A group of dolphins is called a pod.", category: "Nature", level: .level1),
        Factlet(fact: "A group of sharks is called a shiver.", category: "Nature", level: .level1),
        Factlet(fact: "A group of geese is called a gaggle.", category: "Nature", level: .level1),
        Factlet(fact: "A group of zebras is called a dazzle.", category: "Nature", level: .level1),
        Factlet(fact: "A group of giraffes is called a tower.", category: "Nature", level: .level1),
        Factlet(fact: "A group of hippos is called a bloat.", category: "Nature", level: .level1),
        Factlet(fact: "A group of rhinos is called a crash.", category: "Nature", level: .level1),
        Factlet(fact: "A group of tigers is called an ambush.", category: "Nature", level: .level1),
        Factlet(fact: "A group of bears is called a sleuth.", category: "Nature", level: .level1),
        Factlet(fact: "A group of foxes is called a skulk.", category: "Nature", level: .level1),
        Factlet(fact: "A group of rabbits is called a warren.", category: "Nature", level: .level1),
        Factlet(fact: "A group of squirrels is called a scurry.", category: "Nature", level: .level1),
        Factlet(fact: "A group of deer is called a herd.", category: "Nature", level: .level1),
        Factlet(fact: "A group of horses is called a herd.", category: "Nature", level: .level1),
        Factlet(fact: "A group of cats is called a clowder.", category: "Nature", level: .level1),
        Factlet(fact: "A group of dogs is called a pack.", category: "Nature", level: .level1),
        Factlet(fact: "A group of pigs is called a sounder.", category: "Nature", level: .level1),
        Factlet(fact: "A group of sheep is called a flock.", category: "Nature", level: .level1),
        Factlet(fact: "A group of goats is called a trip.", category: "Nature", level: .level1),
        Factlet(fact: "A group of chickens is called a flock.", category: "Nature", level: .level1),
        Factlet(fact: "A group of turkeys is called a rafter.", category: "Nature", level: .level1),
        Factlet(fact: "A group of ducks is called a paddling.", category: "Nature", level: .level1),
        Factlet(fact: "A group of swans is called a bevy.", category: "Nature", level: .level1),
        Factlet(fact: "A group of eagles is called a convocation.", category: "Nature", level: .level1),
        Factlet(fact: "A group of hawks is called a cast.", category: "Nature", level: .level1),
        Factlet(fact: "A group of vultures is called a wake.", category: "Nature", level: .level1),
        Factlet(fact: "A group of peacocks is called a muster.", category: "Nature", level: .level1),
        Factlet(fact: "A group of penguins is called a colony.", category: "Nature", level: .level1),
        Factlet(fact: "A group of seals is called a pod.", category: "Nature", level: .level1),
        
        // Nature - Level 2
        Factlet(fact: "Sloths can hold their breath longer than dolphins—up to 40 minutes by slowing their heart rate.", category: "Nature", level: .level2),
        Factlet(fact: "The oldest known living tree is a bristlecone pine named Methuselah, which is over 4,850 years old.", category: "Nature", level: .level2),
        Factlet(fact: "Sharks have been around for over 400 million years, predating dinosaurs by about 200 million years.", category: "Nature", level: .level2),
        Factlet(fact: "A single bee colony can contain up to 60,000 bees.", category: "Nature", level: .level2),
        Factlet(fact: "Elephants are the only mammals that can't jump.", category: "Nature", level: .level2),
        Factlet(fact: "A group of kangaroos is called a mob.", category: "Nature", level: .level2),
        Factlet(fact: "The tongue of a blue whale can weigh as much as an elephant.", category: "Nature", level: .level2),
        Factlet(fact: "Octopuses have three hearts and can change color in less than a second to blend with their surroundings.", category: "Nature", level: .level2),
        Factlet(fact: "A single redwood tree can produce over 2 million seeds in a year.", category: "Nature", level: .level2),
        Factlet(fact: "The platypus is one of only two mammals that lay eggs, the other being the echidna.", category: "Nature", level: .level2),
        Factlet(fact: "A group of ravens is called an unkindness.", category: "Nature", level: .level2),
        Factlet(fact: "A single mature tree can absorb up to 48 pounds of carbon dioxide per year.", category: "Nature", level: .level2),
        Factlet(fact: "The arctic tern migrates from the Arctic to Antarctica and back each year, traveling about 44,000 miles.", category: "Nature", level: .level2),
        Factlet(fact: "A group of jellyfish is called a smack.", category: "Nature", level: .level2),
        Factlet(fact: "A single mushroom can produce billions of spores.", category: "Nature", level: .level2),
        Factlet(fact: "The hummingbird is the only bird that can fly backwards.", category: "Nature", level: .level2),
        Factlet(fact: "A group of porcupines is called a prickle.", category: "Nature", level: .level2),
        Factlet(fact: "A single mature oak tree can support over 500 different species of insects and animals.", category: "Nature", level: .level2),
        Factlet(fact: "The blue whale is the largest animal ever known to have existed, reaching lengths of 100 feet.", category: "Nature", level: .level2),
        Factlet(fact: "The African elephant is the largest land animal, weighing up to 14,000 pounds.", category: "Nature", level: .level2),
        Factlet(fact: "The giraffe is the tallest mammal, with necks reaching up to 6 feet in length.", category: "Nature", level: .level2),
        Factlet(fact: "The cheetah is the fastest land animal, capable of speeds up to 70 miles per hour.", category: "Nature", level: .level2),
        Factlet(fact: "The peregrine falcon is the fastest bird, diving at speeds over 200 miles per hour.", category: "Nature", level: .level2),
        Factlet(fact: "The sailfish is the fastest fish, reaching speeds of 68 miles per hour.", category: "Nature", level: .level2),
        Factlet(fact: "The Arctic tern has the longest migration, traveling 44,000 miles annually between poles.", category: "Nature", level: .level2),
        Factlet(fact: "The bar-tailed godwit can fly non-stop for 7,000 miles during migration.", category: "Nature", level: .level2),
        Factlet(fact: "The wandering albatross has the largest wingspan of any bird, reaching 11 feet.", category: "Nature", level: .level2),
        Factlet(fact: "The bee hummingbird is the smallest bird, weighing less than a penny.", category: "Nature", level: .level2),
        Factlet(fact: "The bumblebee bat is the smallest mammal, weighing less than a penny.", category: "Nature", level: .level2),
        Factlet(fact: "The giant sequoia is the largest tree by volume, with trunks over 30 feet in diameter.", category: "Nature", level: .level2),
        Factlet(fact: "The coast redwood is the tallest tree, reaching heights over 380 feet.", category: "Nature", level: .level2),
        Factlet(fact: "The baobab tree can store up to 32,000 gallons of water in its trunk.", category: "Nature", level: .level2),
        Factlet(fact: "The corpse flower is the largest flower, reaching 3 feet in diameter and smelling like rotting flesh.", category: "Nature", level: .level2),
        Factlet(fact: "The rafflesia is the largest individual flower, weighing up to 15 pounds.", category: "Nature", level: .level2),
        Factlet(fact: "The giant kelp is the fastest-growing plant, growing up to 2 feet per day.", category: "Nature", level: .level2),
        Factlet(fact: "The venus flytrap can close its trap in less than a second to catch insects.", category: "Nature", level: .level2),
        Factlet(fact: "The pitcher plant uses a pool of digestive enzymes to trap and digest insects.", category: "Nature", level: .level2),
        Factlet(fact: "The sundew plant uses sticky tentacles to catch and digest insects.", category: "Nature", level: .level2),
        Factlet(fact: "The bladderwort is an aquatic plant that uses vacuum-powered traps to catch prey.", category: "Nature", level: .level2),
        Factlet(fact: "The giant panda spends 12 hours a day eating bamboo, consuming up to 40 pounds daily.", category: "Nature", level: .level2),
        Factlet(fact: "The koala sleeps up to 22 hours a day, one of the sleepiest animals.", category: "Nature", level: .level2),
        Factlet(fact: "The three-toed sloth moves so slowly that algae grows on its fur, providing camouflage.", category: "Nature", level: .level2),
        Factlet(fact: "The arctic fox can survive temperatures as low as -58°F without shivering.", category: "Nature", level: .level2),
        Factlet(fact: "The camel can survive without water for up to 2 weeks in the desert.", category: "Nature", level: .level2),
        Factlet(fact: "The kangaroo rat can survive its entire life without drinking water, getting moisture from seeds.", category: "Nature", level: .level2),
        Factlet(fact: "The deep-sea anglerfish uses a bioluminescent lure to attract prey in the dark ocean depths.", category: "Nature", level: .level2),
        Factlet(fact: "The mantis shrimp has the most complex eyes in the animal kingdom, seeing 12 primary colors.", category: "Nature", level: .level2),
        Factlet(fact: "The chameleon can move its eyes independently, giving it 360-degree vision.", category: "Nature", level: .level2),
        Factlet(fact: "The star-nosed mole has 22 fleshy appendages on its nose, making it the fastest-eating mammal.", category: "Nature", level: .level2),
        
        // Nature - Level 3
        Factlet(fact: "The mantis shrimp can punch with the speed of a .22 caliber bullet, creating cavitation bubbles that generate heat.", category: "Nature", level: .level3),
        Factlet(fact: "The immortal jellyfish can revert to its juvenile form after reaching maturity, potentially living forever.", category: "Nature", level: .level3),
        Factlet(fact: "The axolotl can regenerate entire limbs, parts of its brain, and even its heart.", category: "Nature", level: .level3),
        Factlet(fact: "The tardigrade, or water bear, can survive extreme conditions including space, radiation, and temperatures near absolute zero.", category: "Nature", level: .level3),
        Factlet(fact: "The Venus flytrap can count. It needs to be touched twice within 20 seconds to close its trap.", category: "Nature", level: .level3),
        
        // Language - Level 1
        Factlet(fact: "'Dreamt' is the only English word that ends with the letters 'mt.'", category: "Language", level: .level1),
        Factlet(fact: "The sentence 'The quick brown fox jumps over the lazy dog' uses every letter of the alphabet.", category: "Language", level: .level1),
        Factlet(fact: "'Bookkeeper' is the only English word with three consecutive double letters.", category: "Language", level: .level1),
        Factlet(fact: "The dot over the letters 'i' and 'j' is called a tittle.", category: "Language", level: .level1),
        Factlet(fact: "The shortest complete sentence in English is 'I am.'", category: "Language", level: .level1),
        Factlet(fact: "The word 'alphabet' comes from the first two letters of the Greek alphabet: alpha and beta.", category: "Language", level: .level1),
        Factlet(fact: "There are more English words beginning with 'S' than any other letter.", category: "Language", level: .level1),
        Factlet(fact: "The word 'queue' is the only word in English that is still pronounced the same way when the last four letters are removed.", category: "Language", level: .level1),
        
        // Language - Level 2
        Factlet(fact: "A 'jiffy' is an actual unit of time: 1/100th of a second.", category: "Language", level: .level2),
        Factlet(fact: "The word 'set' has more definitions than any other word in the English language—over 430 different meanings.", category: "Language", level: .level2),
        Factlet(fact: "The word 'uncopyrightable' is the longest English word that doesn't repeat any letters.", category: "Language", level: .level2),
        Factlet(fact: "The word 'oxymoron' is itself an oxymoron—it comes from Greek words meaning 'sharp' and 'dull.'", category: "Language", level: .level2),
        Factlet(fact: "The longest word without vowels in English is 'rhythms.'", category: "Language", level: .level2),
        Factlet(fact: "The word 'almost' is the longest common English word with all letters in alphabetical order.", category: "Language", level: .level2),
        Factlet(fact: "The word 'strengths' is the longest English word with only one vowel.", category: "Language", level: .level2),
        Factlet(fact: "The word 'therein' contains 10 words without rearranging any letters: the, there, he, in, rein, her, here, ere, therein, herein.", category: "Language", level: .level2),
        Factlet(fact: "The word 'typewriter' is the longest word that can be typed using only the top row of a QWERTY keyboard.", category: "Language", level: .level2),
        
        // Language - Level 3
        Factlet(fact: "The longest word in English has 189,819 letters and takes over 3 hours to pronounce. It's the chemical name for titin.", category: "Language", level: .level3),
        Factlet(fact: "The word 'subbookkeeper' is the only English word with four consecutive double letters.", category: "Language", level: .level3),
        Factlet(fact: "The word 'pneumonoultramicroscopicsilicovolcanoconiosis' is the longest word in major English dictionaries at 45 letters.", category: "Language", level: .level3),
        Factlet(fact: "The word 'abstemious' contains all five vowels in order.", category: "Language", level: .level3),
        Factlet(fact: "The word 'facetious' contains all five vowels in order.", category: "Language", level: .level3),
        Factlet(fact: "The word 'rhythm' is the longest English word without a traditional vowel (a, e, i, o, u).", category: "Language", level: .level3),
        Factlet(fact: "The word 'queueing' is the only English word with five consecutive vowels.", category: "Language", level: .level3),
        
        // Culture - Level 1
        Factlet(fact: "There are more possible iterations of a game of chess than there are atoms in the observable universe.", category: "Culture", level: .level1),
        Factlet(fact: "Japan has more than 50,000 people who are over 100 years old.", category: "Culture", level: .level1),
        Factlet(fact: "The first recorded recipe for chocolate dates back to 1500 BCE in Mesoamerica.", category: "Culture", level: .level1),
        Factlet(fact: "The first movie ever made was 'Roundhay Garden Scene' in 1888, lasting only 2.11 seconds.", category: "Culture", level: .level1),
        Factlet(fact: "The first recorded use of the word 'hello' as a greeting was in 1827.", category: "Culture", level: .level1),
        Factlet(fact: "The first recorded use of the hashtag symbol (#) was in 2007 by Twitter user Chris Messina.", category: "Culture", level: .level1),
        Factlet(fact: "The first recorded use of the word 'selfie' was in 2002, but it didn't become popular until 2013.", category: "Culture", level: .level1),
        
        // Culture - Level 2
        Factlet(fact: "The world's oldest known musical instrument is a 40,000-year-old flute made from a vulture bone.", category: "Culture", level: .level2),
        Factlet(fact: "The world's oldest known piece of chewing gum is over 9,000 years old, found in Sweden.", category: "Culture", level: .level2),
        Factlet(fact: "The world's oldest known recipe is for beer, dating back to 3,900 BCE in ancient Mesopotamia.", category: "Culture", level: .level2),
        Factlet(fact: "The world's oldest known musical notation dates back to 3,400 years ago in ancient Syria.", category: "Culture", level: .level2),
        Factlet(fact: "The first recorded use of the word 'internet' was in 1974, but the concept dates back to the 1960s.", category: "Culture", level: .level2),
        Factlet(fact: "The world's oldest known piece of jewelry is a 100,000-year-old shell necklace found in Morocco.", category: "Culture", level: .level2),
        Factlet(fact: "The first recorded use of the word 'emoji' was in 1997, combining the Japanese words for 'picture' and 'character.'", category: "Culture", level: .level2),
        Factlet(fact: "The world's oldest known painting is over 45,000 years old, found in a cave in Indonesia.", category: "Culture", level: .level2),
        Factlet(fact: "The first recorded use of the word 'blog' was in 1999, as a shortened form of 'weblog.'", category: "Culture", level: .level2),
        Factlet(fact: "The world's oldest known sculpture is the Venus of Hohle Fels, dating back 40,000 years.", category: "Culture", level: .level2),
        Factlet(fact: "The first recorded use of the word 'podcast' was in 2004, combining 'iPod' and 'broadcast.'", category: "Culture", level: .level2),
        Factlet(fact: "The world's oldest known musical instrument ensemble dates back 9,000 years in China.", category: "Culture", level: .level2),
        
        // Culture - Level 3
        Factlet(fact: "The first recorded use of the word 'emoji' in English was in 1997, but emojis weren't standardized until 2010.", category: "Culture", level: .level3),
        
        // The Body - Level 1
        Factlet(fact: "Your nose can remember 50,000 different scents.", category: "The Body", level: .level1),
        Factlet(fact: "The human brain uses about 20% of the body's total energy, despite being only 2% of its weight.", category: "The Body", level: .level1),
        Factlet(fact: "You are taller in the morning than in the evening due to spinal compression throughout the day.", category: "The Body", level: .level1),
        Factlet(fact: "Humans share about 60% of their DNA with bananas.", category: "The Body", level: .level1),
        Factlet(fact: "Your stomach gets a new lining every 3-4 days to prevent it from digesting itself.", category: "The Body", level: .level1),
        Factlet(fact: "The human eye can distinguish about 10 million different colors.", category: "The Body", level: .level1),
        Factlet(fact: "Fingernails grow nearly 4 times faster than toenails.", category: "The Body", level: .level1),
        Factlet(fact: "The strongest muscle in the human body, relative to its size, is the masseter (jaw muscle).", category: "The Body", level: .level1),
        Factlet(fact: "Your heart beats about 100,000 times per day, pumping approximately 2,000 gallons of blood.", category: "The Body", level: .level1),
        Factlet(fact: "Your skin is the largest organ in your body, covering about 20 square feet in adults.", category: "The Body", level: .level1),
        Factlet(fact: "The human brain contains approximately 86 billion neurons.", category: "The Body", level: .level1),
        
        // The Body - Level 2
        Factlet(fact: "The human body contains enough iron to make a 3-inch nail.", category: "The Body", level: .level2),
        Factlet(fact: "You produce about 1.5 liters of saliva every day, enough to fill two bathtubs per year.", category: "The Body", level: .level2),
        Factlet(fact: "The human body has about 60,000 miles of blood vessels—enough to circle the Earth twice.", category: "The Body", level: .level2),
        Factlet(fact: "Your bones are stronger than steel, but lighter than concrete.", category: "The Body", level: .level2),
        Factlet(fact: "The human body produces about 25 million new cells every second.", category: "The Body", level: .level2),
        Factlet(fact: "Your tongue has about 10,000 taste buds, but they're not just on your tongue—they're also in your throat and roof of your mouth.", category: "The Body", level: .level2),
        Factlet(fact: "The human body contains enough carbon to fill about 9,000 pencils.", category: "The Body", level: .level2),
        Factlet(fact: "Your eyes can process 36,000 pieces of information per hour.", category: "The Body", level: .level2),
        Factlet(fact: "The human body contains enough phosphorus to make 2,200 match heads.", category: "The Body", level: .level2),
        Factlet(fact: "Your brain generates about 12-25 watts of electricity—enough to power a dim light bulb.", category: "The Body", level: .level2),
        Factlet(fact: "The human body has about 37 trillion cells, but only about 43% are human cells—the rest are bacteria.", category: "The Body", level: .level2),
        Factlet(fact: "Your heart creates enough pressure to squirt blood 30 feet.", category: "The Body", level: .level2),
        Factlet(fact: "The human body contains enough fat to make 7 bars of soap.", category: "The Body", level: .level2),
        Factlet(fact: "Your brain uses about 20% of your body's total oxygen supply.", category: "The Body", level: .level2),
        Factlet(fact: "The human body produces about 1.5 liters of mucus every day.", category: "The Body", level: .level2),
        Factlet(fact: "Your bones are constantly being broken down and rebuilt—you get a new skeleton about every 10 years.", category: "The Body", level: .level2),
        Factlet(fact: "The human body contains enough water to fill a 10-gallon tank.", category: "The Body", level: .level2),
        Factlet(fact: "Your brain can process images in as little as 13 milliseconds.", category: "The Body", level: .level2),
        
        // The Body - Level 3
        Factlet(fact: "The human body contains enough sulfur to kill all fleas on an average dog.", category: "The Body", level: .level3),
        
        // Geography - Level 1
        Factlet(fact: "Russia has 11 time zones, more than any other country.", category: "Geography", level: .level1),
        Factlet(fact: "Canada has more lakes than the rest of the world combined.", category: "Geography", level: .level1),
        Factlet(fact: "Mount Everest grows about 4 millimeters every year due to tectonic activity.", category: "Geography", level: .level1),
        Factlet(fact: "The Dead Sea is so salty that nothing can live in it, and you float effortlessly on its surface.", category: "Geography", level: .level1),
        Factlet(fact: "Antarctica is the only continent without a time zone.", category: "Geography", level: .level1),
        Factlet(fact: "The Pacific Ocean is larger than all the land on Earth combined.", category: "Geography", level: .level1),
        Factlet(fact: "There is a town in Norway called Hell, and it freezes over every winter.", category: "Geography", level: .level1),
        Factlet(fact: "The Sahara Desert is expanding by about 30 miles per year.", category: "Geography", level: .level1),
        Factlet(fact: "The deepest point on Earth is the Mariana Trench in the Pacific Ocean, reaching 36,070 feet deep.", category: "Geography", level: .level1),
        Factlet(fact: "The longest river in the world is the Nile, stretching about 4,135 miles through 11 countries.", category: "Geography", level: .level1),
        Factlet(fact: "The largest desert in the world is Antarctica, not the Sahara. Deserts are defined by precipitation, not temperature.", category: "Geography", level: .level1),
        Factlet(fact: "The highest waterfall in the world is Angel Falls in Venezuela, dropping 3,212 feet.", category: "Geography", level: .level1),
        
        // Geography - Level 2
        Factlet(fact: "Australia is wider than the Moon. Australia is about 2,485 miles wide, while the Moon's diameter is about 2,159 miles.", category: "Geography", level: .level2),
        Factlet(fact: "The smallest country in the world is Vatican City, covering just 0.17 square miles.", category: "Geography", level: .level2),
        Factlet(fact: "The largest country in the world is Russia, covering about 6.6 million square miles.", category: "Geography", level: .level2),
        Factlet(fact: "The longest mountain range in the world is underwater—the Mid-Ocean Ridge stretches about 40,000 miles.", category: "Geography", level: .level2),
        Factlet(fact: "The hottest place on Earth is Death Valley, California, where temperatures can reach 134°F.", category: "Geography", level: .level2),
        Factlet(fact: "The coldest place on Earth is Antarctica, where temperatures can drop to -128.6°F.", category: "Geography", level: .level2),
        Factlet(fact: "The largest ocean is the Pacific Ocean, covering about 63 million square miles.", category: "Geography", level: .level2),
        Factlet(fact: "The smallest ocean is the Arctic Ocean, covering about 5.4 million square miles.", category: "Geography", level: .level2),
        Factlet(fact: "The longest coastline in the world belongs to Canada, stretching about 125,567 miles.", category: "Geography", level: .level2),
        Factlet(fact: "The highest point on Earth is Mount Everest at 29,032 feet above sea level.", category: "Geography", level: .level2),
        Factlet(fact: "The lowest point on Earth is the Dead Sea, which is 1,412 feet below sea level.", category: "Geography", level: .level2),
        Factlet(fact: "The largest lake in the world is the Caspian Sea, covering about 143,000 square miles.", category: "Geography", level: .level2),
        Factlet(fact: "The deepest lake in the world is Lake Baikal in Russia, reaching 5,387 feet deep.", category: "Geography", level: .level2),
        Factlet(fact: "The longest border between two countries is between Canada and the United States, stretching 5,525 miles.", category: "Geography", level: .level2),
        Factlet(fact: "The most populated country in the world is China, with over 1.4 billion people.", category: "Geography", level: .level2),
        Factlet(fact: "The least populated country in the world is Vatican City, with about 800 residents.", category: "Geography", level: .level2),
        Factlet(fact: "The largest island in the world is Greenland, covering about 836,000 square miles.", category: "Geography", level: .level2),
        Factlet(fact: "The most densely populated country in the world is Monaco, with about 19,000 people per square mile.", category: "Geography", level: .level2),
        
        // Geography - Level 3
        Factlet(fact: "The longest river in Europe is the Volga, stretching about 2,294 miles through Russia.", category: "Geography", level: .level3),
        Factlet(fact: "The largest country without a coastline is Kazakhstan, covering about 1.05 million square miles.", category: "Geography", level: .level3),
        Factlet(fact: "The most isolated island in the world is Tristan da Cunha, located 1,500 miles from the nearest inhabited land.", category: "Geography", level: .level3),
        
        // Technology - Level 1
        Factlet(fact: "The first ever website is still online at info.cern.ch.", category: "Technology", level: .level1),
        Factlet(fact: "The average smartphone has more computing power than all of NASA in 1969.", category: "Technology", level: .level1),
        Factlet(fact: "Email is older than the World Wide Web. The first email was sent in 1971, while the web was invented in 1989.", category: "Technology", level: .level1),
        Factlet(fact: "The first computer mouse was made of wood.", category: "Technology", level: .level1),
        Factlet(fact: "About 90% of the world's currency exists only digitally.", category: "Technology", level: .level1),
        Factlet(fact: "The QWERTY keyboard was designed to slow down typing to prevent typewriter jams.", category: "Technology", level: .level1),
        Factlet(fact: "More people in the world have access to mobile phones than to toilets.", category: "Technology", level: .level1),
        Factlet(fact: "The first text message was sent in 1992 and read 'Merry Christmas.'", category: "Technology", level: .level1),
        Factlet(fact: "The first iPhone was released in 2007 and didn't have copy and paste functionality.", category: "Technology", level: .level1),
        Factlet(fact: "The first computer weighed 30 tons and occupied 1,800 square feet when it was built in 1946.", category: "Technology", level: .level1),
        
        // Technology - Level 2
        Factlet(fact: "The first 1GB hard drive, introduced in 1980, weighed over 500 pounds and cost $40,000.", category: "Technology", level: .level2),
        Factlet(fact: "The first computer bug was an actual bug—a moth found trapped in the Harvard Mark II computer in 1947.", category: "Technology", level: .level2),
        Factlet(fact: "The first digital camera was invented in 1975 and took 23 seconds to capture a single image.", category: "Technology", level: .level2),
        Factlet(fact: "The first computer virus was created in 1983 and was called 'Elk Cloner.'", category: "Technology", level: .level2),
        Factlet(fact: "The first webcam was created to monitor a coffee pot at Cambridge University in 1991.", category: "Technology", level: .level2),
        Factlet(fact: "The first domain name ever registered was symbolics.com in 1985.", category: "Technology", level: .level2),
        Factlet(fact: "The first video game was created in 1958 and was called 'Tennis for Two.'", category: "Technology", level: .level2),
        Factlet(fact: "The first email spam message was sent in 1978 to 400 ARPANET users.", category: "Technology", level: .level2),
        Factlet(fact: "The first computer password was used at MIT in 1961.", category: "Technology", level: .level2),
        Factlet(fact: "The first touchscreen was invented in 1965, but it wasn't widely used until the 2000s.", category: "Technology", level: .level2),
        Factlet(fact: "The first computer network was ARPANET, created in 1969, which eventually became the internet.", category: "Technology", level: .level2),
        Factlet(fact: "The first computer graphics were created in 1963 at MIT.", category: "Technology", level: .level2),
        Factlet(fact: "The first computer animation was created in 1960 and showed a bouncing ball.", category: "Technology", level: .level2),
        Factlet(fact: "The first computer game with graphics was 'Spacewar!' created in 1962.", category: "Technology", level: .level2),
        Factlet(fact: "The first computer mouse was invented in 1964 but wasn't widely used until the 1980s.", category: "Technology", level: .level2),
        Factlet(fact: "The first computer printer was invented in 1953 and used a typewriter mechanism.", category: "Technology", level: .level2),
        Factlet(fact: "The first computer monitor was a cathode ray tube (CRT) invented in 1897.", category: "Technology", level: .level2),
        Factlet(fact: "The first computer keyboard was invented in 1868 and was called the 'Type-Writer.'", category: "Technology", level: .level2),
        Factlet(fact: "The first computer storage device was a punch card, invented in 1725.", category: "Technology", level: .level2),
        
        // Technology - Level 3
        Factlet(fact: "The first computer program was written by Ada Lovelace in 1843 for Charles Babbage's Analytical Engine.", category: "Technology", level: .level3),
        Factlet(fact: "The first computer network protocol was TCP/IP, developed in 1974.", category: "Technology", level: .level3),
    ]
    
    static func random() -> Factlet {
        all.randomElement() ?? all[0]
    }
    
    static func randomExcluding(_ current: Factlet?) -> Factlet {
        guard let current = current, all.count > 1 else {
            return random()
        }
        var newFactlet = random()
        while newFactlet.id == current.id && all.count > 1 {
            newFactlet = random()
        }
        return newFactlet
    }
}
