//
//  Factlets.swift
//  Factlet
//
//  Data model and collection of general knowledge factlets
//

import Foundation

struct Factlet: Codable, Identifiable, Equatable {
    let id: UUID
    let fact: String
    let category: String
    
    init(id: UUID = UUID(), fact: String, category: String) {
        self.id = id
        self.fact = fact
        self.category = category
    }
}

// MARK: - Factlet Collection
struct FactletCollection {
    static let all: [Factlet] = [
        // Science
        Factlet(fact: "Honey never spoils. Archaeologists have found 3,000-year-old honey in Egyptian tombs that was still perfectly edible.", category: "Science"),
        Factlet(fact: "A day on Venus is longer than its year. Venus takes 243 Earth days to rotate once, but only 225 Earth days to orbit the Sun.", category: "Science"),
        Factlet(fact: "Octopuses have three hearts and blue blood. Two hearts pump blood to the gills, while the third pumps it to the rest of the body.", category: "Science"),
        Factlet(fact: "Water can boil and freeze at the same time. This phenomenon, called the triple point, occurs at a specific temperature and pressure.", category: "Science"),
        Factlet(fact: "A teaspoon of neutron star would weigh about 6 billion tons.", category: "Science"),
        Factlet(fact: "Bananas are berries, but strawberries are not. Botanically, berries are fruits produced from a single ovary.", category: "Science"),
        Factlet(fact: "Lightning strikes the Earth about 8 million times per day, or roughly 100 times per second.", category: "Science"),
        Factlet(fact: "Your body contains about 37.2 trillion cells, and you lose about 200 billion cells every day.", category: "Science"),
        Factlet(fact: "The speed of light is approximately 186,282 miles per second, or about 670 million miles per hour.", category: "Science"),
        Factlet(fact: "Diamonds are not forever—they can burn. At about 1,652°F, a diamond will start to burn.", category: "Science"),
        Factlet(fact: "There are more atoms in a single glass of water than there are glasses of water in all the oceans on Earth.", category: "Science"),
        Factlet(fact: "A single cloud can weigh more than 1 million pounds, but floats because the air beneath it is even heavier.", category: "Science"),
        Factlet(fact: "The human brain generates about 20 watts of electrical power—enough to power a dim light bulb.", category: "Science"),
        Factlet(fact: "Gold is so rare that all the gold ever mined would fit into a cube about 21 meters on each side.", category: "Science"),
        Factlet(fact: "Helium is the only element that cannot be solidified by lowering temperature alone—it requires pressure too.", category: "Science"),
        Factlet(fact: "A single bolt of lightning contains enough energy to power a 100-watt light bulb for more than 3 months.", category: "Science"),
        Factlet(fact: "The Earth's core is as hot as the surface of the Sun, reaching temperatures of about 9,800°F.", category: "Science"),
        Factlet(fact: "Sound travels about 4 times faster in water than in air.", category: "Science"),
        Factlet(fact: "A single raindrop falling from a cloud can reach speeds of up to 22 miles per hour.", category: "Science"),
        Factlet(fact: "The human eye can detect a single photon of light in perfect darkness.", category: "Science"),
        Factlet(fact: "Glass is actually a liquid, not a solid. It flows very slowly over hundreds of years.", category: "Science"),
        Factlet(fact: "The DNA in your body, if uncoiled, would stretch from the Earth to the Sun and back more than 300 times.", category: "Science"),
        Factlet(fact: "A single teaspoon of soil can contain more living organisms than there are people on Earth.", category: "Science"),
        Factlet(fact: "The Moon is slowly moving away from Earth at a rate of about 1.5 inches per year.", category: "Science"),
        Factlet(fact: "Oxygen makes up about 21% of Earth's atmosphere, but it's only the third most abundant element in the universe.", category: "Science"),
        Factlet(fact: "A single strand of spider silk is stronger than steel of the same diameter.", category: "Science"),
        Factlet(fact: "The human body produces about 1.5 liters of saliva every day.", category: "Science"),
        Factlet(fact: "At absolute zero (-459.67°F), atoms would stop moving completely.", category: "Science"),
        Factlet(fact: "The Great Red Spot on Jupiter is a storm that has been raging for at least 400 years.", category: "Science"),
        Factlet(fact: "A single grain of sand contains about 10 quintillion atoms.", category: "Science"),
        
        // History
        Factlet(fact: "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.", category: "History"),
        Factlet(fact: "Oxford University is older than the Aztec Empire. Teaching began in Oxford in 1096, while the Aztec Empire was founded in 1428.", category: "History"),
        Factlet(fact: "The shortest war in history lasted 38 to 45 minutes between Britain and Zanzibar on August 27, 1896.", category: "History"),
        Factlet(fact: "Ancient Romans used crushed mouse brains as toothpaste.", category: "History"),
        Factlet(fact: "Woolly mammoths were still alive when the Great Pyramid of Giza was being built, around 2660 BCE.", category: "History"),
        Factlet(fact: "The Eiffel Tower was originally intended to be a temporary structure, built for the 1889 World's Fair.", category: "History"),
        Factlet(fact: "Vikings never wore horned helmets. This is a 19th-century myth popularized by costume designers.", category: "History"),
        Factlet(fact: "The first computer programmer was Ada Lovelace, who wrote algorithms for Charles Babbage's Analytical Engine in the 1840s.", category: "History"),
        Factlet(fact: "Napoleon was actually average height for his time—about 5'7\". The myth of his shortness came from British propaganda.", category: "History"),
        Factlet(fact: "The Library of Alexandria, one of the largest libraries of the ancient world, was destroyed over 2,000 years ago.", category: "History"),
        Factlet(fact: "The Great Wall of China is not visible from space with the naked eye, despite the popular myth.", category: "History"),
        Factlet(fact: "The Black Death killed an estimated 75-200 million people in the 14th century, reducing the world population by 30-60%.", category: "History"),
        Factlet(fact: "The first recorded Olympic Games were held in 776 BCE in Olympia, Greece.", category: "History"),
        Factlet(fact: "The Titanic was considered unsinkable, but it sank on its maiden voyage in 1912 after hitting an iceberg.", category: "History"),
        Factlet(fact: "The ancient city of Pompeii was buried under volcanic ash in 79 CE and remained preserved for nearly 1,700 years.", category: "History"),
        Factlet(fact: "The printing press, invented by Johannes Gutenberg around 1440, revolutionized the spread of information.", category: "History"),
        Factlet(fact: "The Berlin Wall stood for 28 years, from 1961 to 1989, dividing East and West Berlin.", category: "History"),
        Factlet(fact: "The first photograph was taken in 1826 by Joseph Nicéphore Niépce, requiring an 8-hour exposure.", category: "History"),
        Factlet(fact: "The ancient Romans used a sponge on a stick, shared by everyone, as toilet paper.", category: "History"),
        Factlet(fact: "The first successful airplane flight by the Wright Brothers lasted only 12 seconds and covered 120 feet.", category: "History"),
        Factlet(fact: "The Rosetta Stone, discovered in 1799, was key to deciphering Egyptian hieroglyphs.", category: "History"),
        Factlet(fact: "The fall of the Roman Empire in 476 CE marked the end of ancient history and the beginning of the Middle Ages.", category: "History"),
        Factlet(fact: "The first telephone call was made by Alexander Graham Bell in 1876, saying 'Mr. Watson, come here.'", category: "History"),
        Factlet(fact: "The ancient Egyptians used papyrus, made from the papyrus plant, as paper over 5,000 years ago.", category: "History"),
        Factlet(fact: "The Industrial Revolution began in Britain in the late 18th century and transformed society worldwide.", category: "History"),
        Factlet(fact: "The first successful heart transplant was performed by Dr. Christiaan Barnard in 1967 in South Africa.", category: "History"),
        Factlet(fact: "The ancient Greeks invented democracy in Athens around 508 BCE.", category: "History"),
        Factlet(fact: "The first computer, ENIAC, weighed 30 tons and occupied 1,800 square feet when it was built in 1946.", category: "History"),
        Factlet(fact: "The Renaissance began in Italy in the 14th century and spread across Europe, marking a cultural rebirth.", category: "History"),
        Factlet(fact: "The first successful vaccine was developed by Edward Jenner in 1796 to prevent smallpox.", category: "History"),
        
        // Nature
        Factlet(fact: "A group of flamingos is called a flamboyance.", category: "Nature"),
        Factlet(fact: "Trees can communicate with each other through an underground network of fungi, sometimes called the 'Wood Wide Web.'", category: "Nature"),
        Factlet(fact: "A single cloud can weigh more than 1 million pounds, but floats because the air beneath it is even heavier.", category: "Nature"),
        Factlet(fact: "Cows have best friends and experience stress when separated from them.", category: "Nature"),
        Factlet(fact: "The Amazon rainforest produces about 20% of the world's oxygen.", category: "Nature"),
        Factlet(fact: "A jellyfish is 95% water. If washed ashore, it would nearly disappear as the water evaporates.", category: "Nature"),
        Factlet(fact: "Sloths can hold their breath longer than dolphins—up to 40 minutes by slowing their heart rate.", category: "Nature"),
        Factlet(fact: "The oldest known living tree is a bristlecone pine named Methuselah, which is over 4,850 years old.", category: "Nature"),
        Factlet(fact: "A group of owls is called a parliament.", category: "Nature"),
        Factlet(fact: "Sharks have been around for over 400 million years, predating dinosaurs by about 200 million years.", category: "Nature"),
        Factlet(fact: "Butterflies taste with their feet. They have taste receptors on their legs to help them find food.", category: "Nature"),
        Factlet(fact: "A blue whale's heart is the size of a small car and can weigh up to 1,300 pounds.", category: "Nature"),
        Factlet(fact: "Dolphins have names for each other. They use signature whistles to identify themselves.", category: "Nature"),
        Factlet(fact: "A single oak tree can produce up to 10,000 acorns in a year.", category: "Nature"),
        Factlet(fact: "Penguins can jump up to 6 feet out of the water onto land.", category: "Nature"),
        Factlet(fact: "A group of crows is called a murder.", category: "Nature"),
        Factlet(fact: "The mantis shrimp can punch with the speed of a .22 caliber bullet, creating cavitation bubbles that generate heat.", category: "Nature"),
        Factlet(fact: "A single bee colony can contain up to 60,000 bees.", category: "Nature"),
        Factlet(fact: "The immortal jellyfish can revert to its juvenile form after reaching maturity, potentially living forever.", category: "Nature"),
        Factlet(fact: "Elephants are the only mammals that can't jump.", category: "Nature"),
        Factlet(fact: "A group of kangaroos is called a mob.", category: "Nature"),
        Factlet(fact: "The tongue of a blue whale can weigh as much as an elephant.", category: "Nature"),
        Factlet(fact: "Octopuses have three hearts and can change color in less than a second to blend with their surroundings.", category: "Nature"),
        Factlet(fact: "A single redwood tree can produce over 2 million seeds in a year.", category: "Nature"),
        Factlet(fact: "The platypus is one of only two mammals that lay eggs, the other being the echidna.", category: "Nature"),
        Factlet(fact: "A group of ravens is called an unkindness.", category: "Nature"),
        Factlet(fact: "The axolotl can regenerate entire limbs, parts of its brain, and even its heart.", category: "Nature"),
        Factlet(fact: "A single mature tree can absorb up to 48 pounds of carbon dioxide per year.", category: "Nature"),
        Factlet(fact: "The arctic tern migrates from the Arctic to Antarctica and back each year, traveling about 44,000 miles.", category: "Nature"),
        Factlet(fact: "A group of jellyfish is called a smack.", category: "Nature"),
        Factlet(fact: "The tardigrade, or water bear, can survive extreme conditions including space, radiation, and temperatures near absolute zero.", category: "Nature"),
        Factlet(fact: "A single mushroom can produce billions of spores.", category: "Nature"),
        Factlet(fact: "The hummingbird is the only bird that can fly backwards.", category: "Nature"),
        Factlet(fact: "A group of porcupines is called a prickle.", category: "Nature"),
        Factlet(fact: "The Venus flytrap can count. It needs to be touched twice within 20 seconds to close its trap.", category: "Nature"),
        Factlet(fact: "A single mature oak tree can support over 500 different species of insects and animals.", category: "Nature"),
        
        // Language
        Factlet(fact: "'Dreamt' is the only English word that ends with the letters 'mt.'", category: "Language"),
        Factlet(fact: "The sentence 'The quick brown fox jumps over the lazy dog' uses every letter of the alphabet.", category: "Language"),
        Factlet(fact: "'Bookkeeper' is the only English word with three consecutive double letters.", category: "Language"),
        Factlet(fact: "The dot over the letters 'i' and 'j' is called a tittle.", category: "Language"),
        Factlet(fact: "A 'jiffy' is an actual unit of time: 1/100th of a second.", category: "Language"),
        Factlet(fact: "The shortest complete sentence in English is 'I am.'", category: "Language"),
        Factlet(fact: "The word 'set' has more definitions than any other word in the English language—over 430 different meanings.", category: "Language"),
        Factlet(fact: "The word 'uncopyrightable' is the longest English word that doesn't repeat any letters.", category: "Language"),
        Factlet(fact: "The longest word in English has 189,819 letters and takes over 3 hours to pronounce. It's the chemical name for titin.", category: "Language"),
        Factlet(fact: "The word 'alphabet' comes from the first two letters of the Greek alphabet: alpha and beta.", category: "Language"),
        Factlet(fact: "There are more English words beginning with 'S' than any other letter.", category: "Language"),
        Factlet(fact: "The word 'queue' is the only word in English that is still pronounced the same way when the last four letters are removed.", category: "Language"),
        Factlet(fact: "The word 'oxymoron' is itself an oxymoron—it comes from Greek words meaning 'sharp' and 'dull.'", category: "Language"),
        Factlet(fact: "The longest word without vowels in English is 'rhythms.'", category: "Language"),
        Factlet(fact: "The word 'almost' is the longest common English word with all letters in alphabetical order.", category: "Language"),
        Factlet(fact: "The word 'strengths' is the longest English word with only one vowel.", category: "Language"),
        Factlet(fact: "The word 'therein' contains 10 words without rearranging any letters: the, there, he, in, rein, her, here, ere, therein, herein.", category: "Language"),
        Factlet(fact: "The word 'typewriter' is the longest word that can be typed using only the top row of a QWERTY keyboard.", category: "Language"),
        Factlet(fact: "The word 'subbookkeeper' is the only English word with four consecutive double letters.", category: "Language"),
        Factlet(fact: "The word 'pneumonoultramicroscopicsilicovolcanoconiosis' is the longest word in major English dictionaries at 45 letters.", category: "Language"),
        Factlet(fact: "The word 'uncopyrightable' is the longest English word that doesn't repeat any letters.", category: "Language"),
        Factlet(fact: "The word 'abstemious' contains all five vowels in order.", category: "Language"),
        Factlet(fact: "The word 'facetious' contains all five vowels in order.", category: "Language"),
        Factlet(fact: "The word 'rhythm' is the longest English word without a traditional vowel (a, e, i, o, u).", category: "Language"),
        Factlet(fact: "The word 'queueing' is the only English word with five consecutive vowels.", category: "Language"),
        
        // Culture
        Factlet(fact: "There are more possible iterations of a game of chess than there are atoms in the observable universe.", category: "Culture"),
        Factlet(fact: "Japan has more than 50,000 people who are over 100 years old.", category: "Culture"),
        Factlet(fact: "The first recorded recipe for chocolate dates back to 1500 BCE in Mesoamerica.", category: "Culture"),
        Factlet(fact: "The world's oldest known musical instrument is a 40,000-year-old flute made from a vulture bone.", category: "Culture"),
        Factlet(fact: "The first movie ever made was 'Roundhay Garden Scene' in 1888, lasting only 2.11 seconds.", category: "Culture"),
        Factlet(fact: "The first recorded use of the word 'hello' as a greeting was in 1827.", category: "Culture"),
        Factlet(fact: "The world's oldest known piece of chewing gum is over 9,000 years old, found in Sweden.", category: "Culture"),
        Factlet(fact: "The first recorded use of the hashtag symbol (#) was in 2007 by Twitter user Chris Messina.", category: "Culture"),
        Factlet(fact: "The world's oldest known recipe is for beer, dating back to 3,900 BCE in ancient Mesopotamia.", category: "Culture"),
        Factlet(fact: "The first recorded use of the word 'selfie' was in 2002, but it didn't become popular until 2013.", category: "Culture"),
        Factlet(fact: "The world's oldest known musical notation dates back to 3,400 years ago in ancient Syria.", category: "Culture"),
        Factlet(fact: "The first recorded use of the word 'internet' was in 1974, but the concept dates back to the 1960s.", category: "Culture"),
        Factlet(fact: "The world's oldest known piece of jewelry is a 100,000-year-old shell necklace found in Morocco.", category: "Culture"),
        Factlet(fact: "The first recorded use of the word 'emoji' was in 1997, combining the Japanese words for 'picture' and 'character.'", category: "Culture"),
        Factlet(fact: "The world's oldest known painting is over 45,000 years old, found in a cave in Indonesia.", category: "Culture"),
        Factlet(fact: "The first recorded use of the word 'blog' was in 1999, as a shortened form of 'weblog.'", category: "Culture"),
        Factlet(fact: "The world's oldest known sculpture is the Venus of Hohle Fels, dating back 40,000 years.", category: "Culture"),
        Factlet(fact: "The first recorded use of the word 'podcast' was in 2004, combining 'iPod' and 'broadcast.'", category: "Culture"),
        Factlet(fact: "The world's oldest known musical instrument ensemble dates back 9,000 years in China.", category: "Culture"),
        Factlet(fact: "The first recorded use of the word 'emoji' in English was in 1997, but emojis weren't standardized until 2010.", category: "Culture"),
        
        // Human Body
        Factlet(fact: "Your nose can remember 50,000 different scents.", category: "Human Body"),
        Factlet(fact: "The human brain uses about 20% of the body's total energy, despite being only 2% of its weight.", category: "Human Body"),
        Factlet(fact: "You are taller in the morning than in the evening due to spinal compression throughout the day.", category: "Human Body"),
        Factlet(fact: "Humans share about 60% of their DNA with bananas.", category: "Human Body"),
        Factlet(fact: "Your stomach gets a new lining every 3-4 days to prevent it from digesting itself.", category: "Human Body"),
        Factlet(fact: "The human eye can distinguish about 10 million different colors.", category: "Human Body"),
        Factlet(fact: "Fingernails grow nearly 4 times faster than toenails.", category: "Human Body"),
        Factlet(fact: "The strongest muscle in the human body, relative to its size, is the masseter (jaw muscle).", category: "Human Body"),
        Factlet(fact: "Your heart beats about 100,000 times per day, pumping approximately 2,000 gallons of blood.", category: "Human Body"),
        Factlet(fact: "The human body contains enough iron to make a 3-inch nail.", category: "Human Body"),
        Factlet(fact: "Your skin is the largest organ in your body, covering about 20 square feet in adults.", category: "Human Body"),
        Factlet(fact: "The human brain contains approximately 86 billion neurons.", category: "Human Body"),
        Factlet(fact: "You produce about 1.5 liters of saliva every day, enough to fill two bathtubs per year.", category: "Human Body"),
        Factlet(fact: "The human body has about 60,000 miles of blood vessels—enough to circle the Earth twice.", category: "Human Body"),
        Factlet(fact: "Your bones are stronger than steel, but lighter than concrete.", category: "Human Body"),
        Factlet(fact: "The human body produces about 25 million new cells every second.", category: "Human Body"),
        Factlet(fact: "Your tongue has about 10,000 taste buds, but they're not just on your tongue—they're also in your throat and roof of your mouth.", category: "Human Body"),
        Factlet(fact: "The human body contains enough carbon to fill about 9,000 pencils.", category: "Human Body"),
        Factlet(fact: "Your eyes can process 36,000 pieces of information per hour.", category: "Human Body"),
        Factlet(fact: "The human body contains enough phosphorus to make 2,200 match heads.", category: "Human Body"),
        Factlet(fact: "Your brain generates about 12-25 watts of electricity—enough to power a dim light bulb.", category: "Human Body"),
        Factlet(fact: "The human body has about 37 trillion cells, but only about 43% are human cells—the rest are bacteria.", category: "Human Body"),
        Factlet(fact: "Your heart creates enough pressure to squirt blood 30 feet.", category: "Human Body"),
        Factlet(fact: "The human body contains enough fat to make 7 bars of soap.", category: "Human Body"),
        Factlet(fact: "Your brain uses about 20% of your body's total oxygen supply.", category: "Human Body"),
        Factlet(fact: "The human body produces about 1.5 liters of mucus every day.", category: "Human Body"),
        Factlet(fact: "Your bones are constantly being broken down and rebuilt—you get a new skeleton about every 10 years.", category: "Human Body"),
        Factlet(fact: "The human body contains enough water to fill a 10-gallon tank.", category: "Human Body"),
        Factlet(fact: "Your brain can process images in as little as 13 milliseconds.", category: "Human Body"),
        Factlet(fact: "The human body contains enough sulfur to kill all fleas on an average dog.", category: "Human Body"),
        
        // Geography
        Factlet(fact: "Russia has 11 time zones, more than any other country.", category: "Geography"),
        Factlet(fact: "Canada has more lakes than the rest of the world combined.", category: "Geography"),
        Factlet(fact: "Mount Everest grows about 4 millimeters every year due to tectonic activity.", category: "Geography"),
        Factlet(fact: "The Dead Sea is so salty that nothing can live in it, and you float effortlessly on its surface.", category: "Geography"),
        Factlet(fact: "Antarctica is the only continent without a time zone.", category: "Geography"),
        Factlet(fact: "The Pacific Ocean is larger than all the land on Earth combined.", category: "Geography"),
        Factlet(fact: "There is a town in Norway called Hell, and it freezes over every winter.", category: "Geography"),
        Factlet(fact: "The Sahara Desert is expanding by about 30 miles per year.", category: "Geography"),
        Factlet(fact: "The deepest point on Earth is the Mariana Trench in the Pacific Ocean, reaching 36,070 feet deep.", category: "Geography"),
        Factlet(fact: "Australia is wider than the Moon. Australia is about 2,485 miles wide, while the Moon's diameter is about 2,159 miles.", category: "Geography"),
        Factlet(fact: "The longest river in the world is the Nile, stretching about 4,135 miles through 11 countries.", category: "Geography"),
        Factlet(fact: "The largest desert in the world is Antarctica, not the Sahara. Deserts are defined by precipitation, not temperature.", category: "Geography"),
        Factlet(fact: "The highest waterfall in the world is Angel Falls in Venezuela, dropping 3,212 feet.", category: "Geography"),
        Factlet(fact: "The smallest country in the world is Vatican City, covering just 0.17 square miles.", category: "Geography"),
        Factlet(fact: "The largest country in the world is Russia, covering about 6.6 million square miles.", category: "Geography"),
        Factlet(fact: "The longest mountain range in the world is underwater—the Mid-Ocean Ridge stretches about 40,000 miles.", category: "Geography"),
        Factlet(fact: "The hottest place on Earth is Death Valley, California, where temperatures can reach 134°F.", category: "Geography"),
        Factlet(fact: "The coldest place on Earth is Antarctica, where temperatures can drop to -128.6°F.", category: "Geography"),
        Factlet(fact: "The largest ocean is the Pacific Ocean, covering about 63 million square miles.", category: "Geography"),
        Factlet(fact: "The smallest ocean is the Arctic Ocean, covering about 5.4 million square miles.", category: "Geography"),
        Factlet(fact: "The longest coastline in the world belongs to Canada, stretching about 125,567 miles.", category: "Geography"),
        Factlet(fact: "The highest point on Earth is Mount Everest at 29,032 feet above sea level.", category: "Geography"),
        Factlet(fact: "The lowest point on Earth is the Dead Sea, which is 1,412 feet below sea level.", category: "Geography"),
        Factlet(fact: "The largest lake in the world is the Caspian Sea, covering about 143,000 square miles.", category: "Geography"),
        Factlet(fact: "The deepest lake in the world is Lake Baikal in Russia, reaching 5,387 feet deep.", category: "Geography"),
        Factlet(fact: "The longest border between two countries is between Canada and the United States, stretching 5,525 miles.", category: "Geography"),
        Factlet(fact: "The most populated country in the world is China, with over 1.4 billion people.", category: "Geography"),
        Factlet(fact: "The least populated country in the world is Vatican City, with about 800 residents.", category: "Geography"),
        Factlet(fact: "The largest island in the world is Greenland, covering about 836,000 square miles.", category: "Geography"),
        Factlet(fact: "The most densely populated country in the world is Monaco, with about 19,000 people per square mile.", category: "Geography"),
        Factlet(fact: "The longest river in Europe is the Volga, stretching about 2,294 miles through Russia.", category: "Geography"),
        Factlet(fact: "The largest country without a coastline is Kazakhstan, covering about 1.05 million square miles.", category: "Geography"),
        Factlet(fact: "The most isolated island in the world is Tristan da Cunha, located 1,500 miles from the nearest inhabited land.", category: "Geography"),
        
        // Technology
        Factlet(fact: "The first ever website is still online at info.cern.ch.", category: "Technology"),
        Factlet(fact: "The average smartphone has more computing power than all of NASA in 1969.", category: "Technology"),
        Factlet(fact: "Email is older than the World Wide Web. The first email was sent in 1971, while the web was invented in 1989.", category: "Technology"),
        Factlet(fact: "The first computer mouse was made of wood.", category: "Technology"),
        Factlet(fact: "About 90% of the world's currency exists only digitally.", category: "Technology"),
        Factlet(fact: "The QWERTY keyboard was designed to slow down typing to prevent typewriter jams.", category: "Technology"),
        Factlet(fact: "The first 1GB hard drive, introduced in 1980, weighed over 500 pounds and cost $40,000.", category: "Technology"),
        Factlet(fact: "More people in the world have access to mobile phones than to toilets.", category: "Technology"),
        Factlet(fact: "The first computer bug was an actual bug—a moth found trapped in the Harvard Mark II computer in 1947.", category: "Technology"),
        Factlet(fact: "The first text message was sent in 1992 and read 'Merry Christmas.'", category: "Technology"),
        Factlet(fact: "The first digital camera was invented in 1975 and took 23 seconds to capture a single image.", category: "Technology"),
        Factlet(fact: "The first computer virus was created in 1983 and was called 'Elk Cloner.'", category: "Technology"),
        Factlet(fact: "The first webcam was created to monitor a coffee pot at Cambridge University in 1991.", category: "Technology"),
        Factlet(fact: "The first domain name ever registered was symbolics.com in 1985.", category: "Technology"),
        Factlet(fact: "The first iPhone was released in 2007 and didn't have copy and paste functionality.", category: "Technology"),
        Factlet(fact: "The first computer weighed 30 tons and occupied 1,800 square feet when it was built in 1946.", category: "Technology"),
        Factlet(fact: "The first video game was created in 1958 and was called 'Tennis for Two.'", category: "Technology"),
        Factlet(fact: "The first email spam message was sent in 1978 to 400 ARPANET users.", category: "Technology"),
        Factlet(fact: "The first computer password was used at MIT in 1961.", category: "Technology"),
        Factlet(fact: "The first touchscreen was invented in 1965, but it wasn't widely used until the 2000s.", category: "Technology"),
        Factlet(fact: "The first computer network was ARPANET, created in 1969, which eventually became the internet.", category: "Technology"),
        Factlet(fact: "The first computer graphics were created in 1963 at MIT.", category: "Technology"),
        Factlet(fact: "The first computer animation was created in 1960 and showed a bouncing ball.", category: "Technology"),
        Factlet(fact: "The first computer game with graphics was 'Spacewar!' created in 1962.", category: "Technology"),
        Factlet(fact: "The first computer mouse was invented in 1964 but wasn't widely used until the 1980s.", category: "Technology"),
        Factlet(fact: "The first computer printer was invented in 1953 and used a typewriter mechanism.", category: "Technology"),
        Factlet(fact: "The first computer monitor was a cathode ray tube (CRT) invented in 1897.", category: "Technology"),
        Factlet(fact: "The first computer keyboard was invented in 1868 and was called the 'Type-Writer.'", category: "Technology"),
        Factlet(fact: "The first computer storage device was a punch card, invented in 1725.", category: "Technology"),
        Factlet(fact: "The first computer program was written by Ada Lovelace in 1843 for Charles Babbage's Analytical Engine.", category: "Technology"),
        Factlet(fact: "The first computer network protocol was TCP/IP, developed in 1974.", category: "Technology"),
    ]
    
    static func random() -> Factlet {
        all.randomElement() ?? all[0]
    }
    
    static func randomExcluding(_ current: Factlet?) -> Factlet {
        guard let current = current, all.count > 1 else {
            return random()
        }
        var newFactlet = random()
        while newFactlet.id == current.id && all.count > 1 {
            newFactlet = random()
        }
        return newFactlet
    }
}
